trigger: none

pool:
  vmImage: ubuntu-latest
#some comment
jobs:
- job: BicepDeployment
  steps:
  
  - task: AzureCLI@2
    inputs:
      azureSubscription: $(ServiceConnectionName)
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: |
       az deployment group create \
       --name $(depnum) \
       --resource-group $(rgName) \
       --template-file main.bicep \
       --parameters appName=$(appName)
